[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"


[font.normal]
family = "JetBrainsMono Nerd Font"

[font]
size = 14

[font.glyph_offset]
x = 0
y = 2

[font.offset]
x = 0
y = 3


[window]
decorations = "none"
opacity = 0.84

[window.padding]
x = 0
y = 0

[colors.primary]
background = '#171720'
foreground = '#dcd7ba'

[colors.normal]
black = '#090618'
red = '#c34043'
green = '#76946a'
yellow = '#c0a36e'
blue = '#7e9cd8'
magenta = '#957fb8'
cyan = '#6a9589'
white = '#c8c093'

[colors.bright]
black = '#727169'
red = '#e82424'
green = '#98bb6c'
yellow = '#e6c384'
blue = '#7fb4ca'
magenta = '#938aa9'
cyan = '#7aa89f'
white = '#dcd7ba'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'
