# colors: https://i.stack.imgur.com/KTSQa.png
# New line at the start of the prompt
add_newline = true

# # Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true


format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
[ ](fg:233 bg:#000000000)\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$cmd_duration\
$custom\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$character"""

# format = """
# [┌─\\[ $directory\\] ](bold blue)$git_branch$git_status$nodejs$rust$lua$go$python$cmd_duration
# [└─](bold blue)$character"""

[aws]
symbol = " "
disabled = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
disabled = true

[cmd_duration]
min_time = 10_000

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 🔒"
read_only_style = "red"
truncate_to_repo = true
truncation_length = 20
style = "bold bg:233 fg:69"
format = "[$path]($style)"

[elixir]
symbol = " "

[elm]
symbol = " "

[gcloud]
disabled = true

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "
disabled = true

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
